### ISSUE TITLE
[Suggestion] See compendium

### ISSUE THREAD

**Issue by 9ryex5** [averrin/alpha-suit#1]
This module is awesome for organization!
A suggestion I have is to be able to see the compendium to which an item belongs when in alpha browser.
Here:
![image](https://user-images.githubusercontent.com/43207603/189359570-f8be0aea-ca06-4914-8f9f-be8aa423cba7.png)

**Comment by averrin** [comment]
Nice idea! I will add it soon.

**Comment by averrin** [comment]
Done in https://github.com/averrin/alpha-suit/releases/tag/0.1.6
