### ISSUE TITLE
Save AlphaSuit Config OR Lock Index Excludes OR Skip Symlinks in Indexing

### ISSUE THREAD

**Issue by buttonpushertv** [averrin/alpha-suit#10]
I think the recent update to v.0.4.10 purged the list of folders I had set up to *not* be indexed. I have 2 giant folders symlinked out of the Data folder, but I fully understand that these folders should not be indexed, so I block them. Because the list of folders that were supposed to be blocked from indexing got cleared without me noticing (or thinking to even check), I just spent a few hours trying to figure out what could possibly be causing Out of Memory errors and random crashes of a previously smoothly running FVTT install (V10.290) I'm sure that AlphaSuit trying to index over 3TB of files is 100% the cause of that, but since I didn't know that that list got cleared, I was beating my head against the wall to figure out why that error started occurring.

Would it be possible to add a feature that would allow for AlphaSuit settings to be exported and/or imported? Or have a setting that locks the Do Not Index fields from being removed or cleared? Or (and maybe this isn't possible due to limited accessible system-level info to FVTT) possibly add any symlinks in the Data folder to the Do Not Index listing by default?

Love the module and will certainly check on it again if ever it starts giving me random OOM errors. Maybe one of these features could help future headaches for people? Thanks.

**Comment by buttonpushertv** [comment]
Oh, I just discovered that AlphaSuit saves the Do Not Index info *locally* - maybe it should be saved to the server instead, so that moving from one system to another doesn't reset our AlphaSuit settings to the defaults.

**Comment by averrin** [comment]
Hi. Yeah, i thought that the indexing mode should be local (like, here is my main and its or to use resources and bandwidth, but here is my "lake house" -- do not use so much traffic). But  "excluded" settings now are local too, and it's definitely a mistake. 
Unfortunately, i suppose foundry API has no enough info to skip symlinks automatically.

Summary: I will move "excluded storages" and "excluded folders" from the client-side to the world storage. Is it a solution for your problem?

**Comment by buttonpushertv** [comment]
Yes. That would be a great way to solve it.

Thanks.

**Comment by averrin** [comment]
Done in https://github.com/averrin/alpha-suit/releases/tag/0.4.11
Feel free to open a new issue with any ideas or bugs.
