### ISSUE TITLE
Compatibility fields are not consistent between different manifest types for v9 and v10

### ISSUE THREAD

**Issue by rikmarais** [averrin/alpha-suit#12]
Hi there 👋 

I noticed that the manifest file's compatibility fields are not consistent between the different manifest types for v9 and v10

**v9**
```
    "minimumCoreVersion": "0.8.6",
    "compatibleCoreVersion": "9",
```
**v10**
```
    "compatibility": {
        "minimum": "9",
        "verified": "10"
    }
```

While I can understand the thought process here (ie. v10+ won't look at the v9 fields, and v9- won't look at the v10 fields), users or integrations might look at both, or either. 

This can create confusion. Forge's Bazaar, for instance, currently references the v9 fields preferentially.
![image](https://user-images.githubusercontent.com/34374883/204840824-af0ce118-097f-4edc-a333-bb3419982ff0.png)

If the same version is compatible across three generations, could we make the compatibility fields consistent too? Thanks!
**v9**
```
    "minimumCoreVersion": "0.8.6",
    "compatibleCoreVersion": "10",
```
**v10**
```
    "compatibility": {
        "minimum": "0.8.6",
        "verified": "10"
    }
```

This should also help with getting more users to install this absolutely epic module!

**Comment by averrin** [comment]
Thank you. I'll fix it in a couple of days.
0.8.6 is a residue of module's template, which I migrated to v10 manually. It's time to clean and update the whole file.

**Comment by averrin** [comment]
Fixed in https://github.com/averrin/alpha-suit/releases/tag/0.5.2
