### ISSUE TITLE
Search Within a Folder

### ISSUE THREAD

**Issue by webmaster94** [averrin/alpha-suit#13]
The search function is great within the file manager, however it has a major flaw. Currently, it searches the entire index at all times. It would be great if you could search within a particular folder and its subfolders instead of searching everything.

**Comment by averrin** [comment]
There is the "filter" field at the bottom of folders window. It filters showed files.
Do you mean a recursive search? I can add such mode for the search...

**Comment by webmaster94** [comment]
I believe the filter only works for files directly in the folder in which the filter is applied. I was hopping to essentially filter the files in the folder and all subfolders as well. Think windows search when you are in a directory.

**Comment by averrin** [comment]
Done in https://github.com/averrin/alpha-suit/releases/tag/0.5.2
