### ISSUE TITLE
What is the Alpha Grid?

### ISSUE THREAD

**Issue by Nedrapter** [averrin/alpha-suit#14]
I couldn't find any info about it. What does it do / What is it's purpose? Also noticed that is available to players too.

**Comment by averrin** [comment]
Yeah, I think I should do something to increase feature discoverability.
Here is the demo: https://youtu.be/m_cWFK2YCGk
If you have more questions feel free to ask them here (even in closed issue) or reach me in Discord: Averrin#0374
