### ISSUE TITLE
[BUG] Item Price

### ISSUE THREAD

**Issue by 9ryex5** [averrin/alpha-suit#15]
**Module Version:** v0.5.4

**Describe the bug**
Alpha Browser isn't able to read item values. Probably since the D&D system introduced currency button.

![image](https://user-images.githubusercontent.com/43207603/227656912-13f3d390-ba2c-4b38-85ed-195ee2d03cba.png)
![image](https://user-images.githubusercontent.com/43207603/227656942-c8ac877e-6f58-43d1-9b7a-abc3d964ce7f.png)

**Comment by averrin** [comment]
Hi, thanks for reporting. Yeah, it's broken by one of the latest system updates. I will fix it in a week.

**Comment by 9ryex5** [comment]
Don't want to press, but I think you forgot this :)

**Comment by averrin** [comment]
Yeah, a busy week. I'd write it down and going to fix this weekend. I appreciate your patience with this.

**Comment by averrin** [comment]
I apologize for unmet expectations, but I finally upload new release with fix
