### ISSUE TITLE
Issues with Compendium Folders custom icons

### ISSUE THREAD

**Issue by earlSt1** [averrin/alpha-suit#2]
Hi, I'm the dev of Compendium Folders and people have been reporting that the folder icons on the sidebar folders have been resetting to an unreachable image (`fa-solid:folder`) every time they refresh the page. I've narrowed it down to this module thats causing it. 

I tried to checkout your module to have a look around but theres a lot of libraries i dont understand how to setup + configure. Could you maybe add a check to see if the folder has an icon already? Then if not you can null it, which will use the fontAwesome folder icons by default.

If you need any assistance feel free to reach out on discord @Erceron#0370

**Comment by averrin** [comment]
Hi. Yeah, it looks like my bug. Thanks, I'll fix it in a couple of days.

**Comment by averrin** [comment]
Fixed in https://github.com/averrin/alpha-suit/releases/tag/0.2.2

**Comment by Hawkeye131** [comment]
Seems to still be happening :(
