### ISSUE TITLE
Drag and Drop Images to Entities

### ISSUE THREAD

**Issue by MrVauxs** [averrin/alpha-suit#4]
It would be a great and I think fitting QoL feature to let Alpha File Manager simply let users drag and drop images into item icons and replace them with the image. An example is shown below.

https://user-images.githubusercontent.com/32039708/198828721-4db659b6-3880-472e-a19e-1af8c5fbe2b9.mp4

**Comment by averrin** [comment]
Yeah! I planned it for manager + tree, but actual entity sheets is much better idea, thanks a lot!

**Comment by averrin** [comment]
Added in https://github.com/averrin/alpha-suit/releases/tag/0.4.1
