### ISSUE TITLE
Suggestions: Option to index on demand instead of on game launch

### ISSUE THREAD

**Issue by grimmash** [averrin/alpha-suit#5]
When doing testing that requires re-loading the game world, Alpha Suit starts indexing immediately with every game launch.  It would be nice to have the option to delay this indexing until either the user opens alpha suit, or have a command within the gui to initiate indexing on demand.

**Comment by averrin** [comment]
Hi. What do you mean "on demand"? Now you can, for example, set negative delay and then start indexing manually from settings. Or you want start indexing on the file manager open? I can do it, but due to long indexing time it can be a bit useless

**Comment by averrin** [comment]
Added in https://github.com/averrin/alpha-suit/releases/tag/0.4.5

**Comment by grimmash** [comment]
I found the delay setting!  

By "On Demand" I mean having the **default** behavior be for Alpha Suit to do no indexing until you actively tell it to build the index.  Right now every time I open a game, AS launches the index, unless I tell it not to via the delay.  This is, from my perspective, undesirable as a default.  Here are some of the reasons:
- For large games this is fairly slow, obviously.  Not a mod issue directly, but if you have enough stuff in world that you want a browser like this, seems like a common case
- Indexing on by default makes reloading worlds while doing any sort of mod/compatibility testing very tedious, because of the reason above.  This may be an artifact of me moving to Foundry v10, but right now I have AS turned off so I do not have to wait for the launch index every time I reload a world. 
- On some of my Forge hosted games manually building the index after the index has already run automatically _seems_ to cause the browser tab to crash (Firefox 106, Foundry v10.288  and using the most recent 5e system and PF2e systems)

Hope that clarifies what the request was!

A good comparison for the use case I see this mod filling is the Compendium Browser mod.  It only covers compendia, and that loads a given compendium when you open the mod and pick a category.  It is a little slower in the moment when you first open it, but it puts off the cost of loading the data until you need it.

**Comment by averrin** [comment]
Actually, I think most of users don't have such big worlds to make indexing long. But I have, so I added a lot of settings for it. Now the search field has dedicated button for indexing start. You can just disable indexing in the settings.
I'll think about changing the default behaviour.
