### ISSUE TITLE
[BUG] Alpha Suit freezing when browsing some directories

### ISSUE THREAD

**Issue by Nedrapter** [averrin/alpha-suit#6]
**Module Version:** v0.4.4

**Describe the bug**
When using the Browser to navigate into a a directory, the Alpa module and all its menus become unresponsive. This behavior was noticed when trying to browse Baileywiki's modules on the Bazaar, specifically the Sound folder.

**To Reproduce**
1. Go to a game that is hosted on the Forge and has Baileywiki's Premium module and Alpha Suit enabled.
2. Use the browser to navigate to:  Forge-bazaar>modules>baileywiki-premium-maps>sounds
3. the following pop up in the console:
![image](https://user-images.githubusercontent.com/74311190/201100572-c250096e-b7ff-4479-9d82-9ae2c92782b3.png)

**Browser:**
 - Opera

**Foundry Version:** 
10.286
**Game System:** 
dnd5e 2.0.3

This also freezes the indexing process if it was running.

**Comment by Nedrapter** [comment]
Update: It is happening on other directories that do not include sounds. Was browsing my Forge Shared compendium and all Alpha Suit functionality froze. The following error appeared: 
![image](https://user-images.githubusercontent.com/74311190/201111064-6c6e58b7-bdc4-477d-bf7b-f751db7d3472.png)

**Comment by averrin** [comment]
Thank you for reporting. Looks like some edge cases should have better error handling

**Comment by averrin** [comment]
Please try https://github.com/averrin/alpha-suit/releases/tag/0.4.6 and reopen this issue if problems are still resent.

**Comment by Nedrapter** [comment]
The folder does open now without freezing Alpha Suit. However it popped 85 errors of this type
![image](https://user-images.githubusercontent.com/74311190/201224814-d9ab532d-845b-48fb-b2f1-7399736aeb65.png)

Not sure if they are related or not to the issue.

**Comment by averrin** [comment]
Unfortunately I don't know for now how to avoid this, because foundry has, for example ".ogg" extension in the "audio" and "video" lists. So I'm trying to get preview even from sounds.
