### ISSUE TITLE
[BUG] Compendium views not matching with Alpha Suit.

### ISSUE THREAD

**Issue by Nedrapter** [averrin/alpha-suit#7]
**Module Version:** v0.4.6

The compendium view does not match with the Alpha Suit

**To Reproduce**
Open a compendium side by side and compare.

![image](https://user-images.githubusercontent.com/74311190/201226220-c45e154b-126e-4b0c-9575-8845c5adfebe.png)

**Browser:**
Opera

**Foundry Version:** 10.283

**Game System:** dnd5e 2.03

So now after being able to browse the compendiums without Alpha Suit freezing, I see that the view does not match the compendium. First the folders seem to be in a random order and then there are spells outside of the folder (but also a duplicate of them inside those folders).

**Comment by averrin** [comment]
1. Seems like I should add sorting for folders... I thought it works.
2. But these extra items outside folders is much more intriguing. Can I test this compendium some way?

**Comment by Nedrapter** [comment]
[spell_compendium.zip](https://github.com/averrin/alpha-suit/files/9992796/spell_compendium.zip)

**Comment by Nedrapter** [comment]
The same happens with another compendium that has playlists

**Comment by Nedrapter** [comment]
I don't know if this is related to this bug or should I open a new topic:  The Alpha Browser, when searching under NPCs, Items, Spells and Feats, does not index anything from my Shared Compendium (the one that has the issues above). It might be missing other compendiums too but I only noticed those, since I use them daily.

**Comment by averrin** [comment]
I'd never touch shared compendiums before, so it's a quite possible that the module works with them in a wrong way. I'll try to fix it in a couple of days.

**Comment by averrin** [comment]
I hope both of issues are fixed in https://github.com/averrin/alpha-suit/releases/tag/0.4.7
Please reopen issue if not.
