### ISSUE TITLE
Persistent file index

### ISSUE THREAD

**Issue by TehT** [averrin/alpha-suit#8]
Having alpha suit index all 60k images from my forgotten adventures folder every time I refresh is getting old, would it be possible to add a manual update, so I can reindex if I change anything, with the caveat that non-indexed files are not searchable?

**Comment by averrin** [comment]
There is already options to disable index and reindex manually. But I think, you are talking about having persistent index... I thought about it. It's difficult, but I have a couple ideas...

**Comment by averrin** [comment]
Implemented here: https://github.com/averrin/alpha-suit/releases/tag/0.4.7 as Premium feature. If you think that its unfair, reach me in Discord (Averrin#0374) and i'll give you the premium unlocker.
