### ISSUE TITLE
UI scale settings not saving

### ISSUE THREAD

**Issue by Nedrapter** [averrin/alpha-suit#9]
**Module Version:** v0.4.7

**Describe the bug**
Changing the UI scale and refreshing, still does not apply the setting.

**To Reproduce**
1. Chang UI %
2. Refresh

**Expected behavior**

**Screenshots**
The following error shows up when changing the scale 
![image](https://user-images.githubusercontent.com/74311190/201806983-9c22f1ee-596c-4e53-91bf-91d6be6e2463.png)

**Browser:**
Opera
**Foundry Version:** 
10.290
**Game System:** 
dnd5e

The setting that was input still shows, however it is not applied. For example I put it to 1.3 . The UI previews as 30% larger as expected. When I refresh, the UI is scaled back to normal, but the setting still says 1.3 .

**Comment by averrin** [comment]
It should be fixed in https://github.com/averrin/alpha-suit/releases/tag/0.4.10
The error on the screenshot isn't fixed yet, but it doesn't affect anything.
